/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class admin {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        ObjectMapper mapper = new ObjectMapper();

        List<club> clubs = new ArrayList<>();
        List<user> users = new ArrayList<>();

        System.out.println("Add number of clubs you want to add");
        int num_club= sc.nextInt();
        sc.nextLine();

        for(int i=0; i<num_club; i++){
            System.out.println("enter the name of club number "+(i+1));
            String name_club = sc.nextLine();

            System.out.println("enter the department of club number "+(i+1));
            String name_dept = sc.nextLine();

            System.out.println("enter the date of interview of club number "+(i+1));
            String name_date = sc.nextLine();

            System.out.println("enter the form link for the club");
            String club_form= sc.nextLine();

            String file_club = name_club+".csv";

            try ( FileWriter member_file = new FileWriter("D:\\json\\app\\src\\main\\java\\org\\example\\"+file_club,true);){
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            File student_data = new File("D:\\json\\app\\src\\main\\java\\org\\example\\"+file_club);

            clubs.add(new club(name_club, name_dept,name_date,club_form));

                try {
                    mapper.writerWithDefaultPrettyPrinter().writeValue(new File("D:\\json\\app\\src\\main\\java\\org\\example\\clubs.json"), clubs);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }

        }
        String[] headers = {"name","department","interview date","link"};
        try(CSVPrinter printer = new CSVPrinter(new FileWriter("D:\\json\\app\\src\\main\\java\\org\\example\\clubs.csv"),CSVFormat.EXCEL);) {
            clubs.forEach(e->{
                try {
                    printer.printRecord(e.getClubname(),e.getDepartment(),e.getDate(),e.getForm());
                } catch (IOException ex) {
                    throw new RuntimeException(ex);
                }
            });
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }
}

