/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        admin classUnderTest = new admin();
        assertNotNull("admin object should not be null", classUnderTest);
    }
}
